/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */
package com.lf.lfopen.webservices.domain.user.json;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * (no documentation provided)
 */
public class LFUser implements java.io.Serializable {

  @JsonIgnore
  private java.lang.Short _age;
  @JsonIgnore
  private java.lang.String _firstName;
  @JsonIgnore
  private java.lang.String _lastName;
  @JsonIgnore
  private java.lang.String _nickName;
  @JsonIgnore
  private java.lang.String _gender;
  @JsonIgnore
  private java.lang.String _emailAddress;
  @JsonIgnore
  private java.lang.Double _height;
  @JsonIgnore
  private java.lang.String _heightUnit;
  @JsonIgnore
  private java.lang.Double _weight;
  @JsonIgnore
  private java.lang.String _weightUnit;
  @JsonIgnore
  private java.lang.String _preferredUnit;
  @JsonIgnore
  private java.util.Date _createdOn;

  /**
   * Age of the user.
   */
  @JsonProperty("age")
  public java.lang.Short getAge() {
    return this._age;
  }

  /**
   * Age of the user.
   */
  @JsonProperty("age")
  public void setAge(java.lang.Short _age) {
    this._age = _age;
  }

  /**
   * First name of the LFconnect user.
   */
  @JsonProperty("firstName")
  public java.lang.String getFirstName() {
    return this._firstName;
  }

  /**
   * First name of the LFconnect user.
   */
  @JsonProperty("firstName")
  public void setFirstName(java.lang.String _firstName) {
    this._firstName = _firstName;
  }

  /**
   * Last name of the LFconnect user.
   */
  @JsonProperty("lastName")
  public java.lang.String getLastName() {
    return this._lastName;
  }

  /**
   * Last name of the LFconnect user.
   */
  @JsonProperty("lastName")
  public void setLastName(java.lang.String _lastName) {
    this._lastName = _lastName;
  }

  /**
   * Nickname of the LFconnect user.
   */
  @JsonProperty("nickName")
  public java.lang.String getNickName() {
    return this._nickName;
  }

  /**
   * Nickname of the LFconnect user.
   */
  @JsonProperty("nickName")
  public void setNickName(java.lang.String _nickName) {
    this._nickName = _nickName;
  }

  /**
   * Gender of the Virtual Trainer User.
   * Possible values:
   * m/M - Male
   * f/F - Female
   */
  @JsonProperty("gender")
  public java.lang.String getGender() {
    return this._gender;
  }

  /**
   * Gender of the Virtual Trainer User.
   * Possible values:
   * m/M - Male
   * f/F - Female
   */
  @JsonProperty("gender")
  public void setGender(java.lang.String _gender) {
    this._gender = _gender;
  }

  /**
   * Email address registered of the LFconnect user.
   */
  @JsonProperty("emailAddress")
  public java.lang.String getEmailAddress() {
    return this._emailAddress;
  }

  /**
   * Email address registered of the LFconnect user.
   */
  @JsonProperty("emailAddress")
  public void setEmailAddress(java.lang.String _emailAddress) {
    this._emailAddress = _emailAddress;
  }

  /**
   * Height of the LFconnect user.
   */
  @JsonProperty("height")
  public java.lang.Double getHeight() {
    return this._height;
  }

  /**
   * Height of the LFconnect user.
   */
  @JsonProperty("height")
  public void setHeight(java.lang.Double _height) {
    this._height = _height;
  }

  /**
   * Unit used in the user's height value.
   * Possible values:
   * I - Imperial (meaning height is in inches)
   * M - Metric (meaning height is in cms)
   */
  @JsonProperty("heightUnit")
  public java.lang.String getHeightUnit() {
    return this._heightUnit;
  }

  /**
   * Unit used in the user's height value.
   * Possible values:
   * I - Imperial (meaning height is in inches)
   * M - Metric (meaning height is in cms)
   */
  @JsonProperty("heightUnit")
  public void setHeightUnit(java.lang.String _heightUnit) {
    this._heightUnit = _heightUnit;
  }

  /**
   * Weight of the LFconnect user.
   */
  @JsonProperty("weight")
  public java.lang.Double getWeight() {
    return this._weight;
  }

  /**
   * Weight of the LFconnect user.
   */
  @JsonProperty("weight")
  public void setWeight(java.lang.Double _weight) {
    this._weight = _weight;
  }

  /**
   * Unit used in the user's weight value.
   * Possible values:
   * I - Imperial
   * M - Metric
   */
  @JsonProperty("weightUnit")
  public java.lang.String getWeightUnit() {
    return this._weightUnit;
  }

  /**
   * Unit used in the user's weight value.
   * Possible values:
   * I - Imperial
   * M - Metric
   */
  @JsonProperty("weightUnit")
  public void setWeightUnit(java.lang.String _weightUnit) {
    this._weightUnit = _weightUnit;
  }

  /**
   * User's prefered unit used in the workouts, etc.
   * Possible values:
   * I - Imperial
   * M - Metric
   */
  @JsonProperty("preferredUnit")
  public java.lang.String getPreferredUnit() {
    return this._preferredUnit;
  }

  /**
   * User's prefered unit used in the workouts, etc.
   * Possible values:
   * I - Imperial
   * M - Metric
   */
  @JsonProperty("preferredUnit")
  public void setPreferredUnit(java.lang.String _preferredUnit) {
    this._preferredUnit = _preferredUnit;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("createdOn")
  public java.util.Date getCreatedOn() {
    return this._createdOn;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("createdOn")
  public void setCreatedOn(java.util.Date _createdOn) {
    this._createdOn = _createdOn;
  }
}
