/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */
package com.lf.lfopen.webservices.domain.workoutpreset.json;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * (no documentation provided)
 */
public class Activity implements java.io.Serializable {

  @JsonIgnore
  private java.lang.Long _activityId;
  @JsonIgnore
  private java.lang.String _activityName;

  /**
   * (no documentation provided)
   */
  @JsonProperty("activityId")
  public java.lang.Long getActivityId() {
    return this._activityId;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("activityId")
  public void setActivityId(java.lang.Long _activityId) {
    this._activityId = _activityId;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("activityName")
  public java.lang.String getActivityName() {
    return this._activityName;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("activityName")
  public void setActivityName(java.lang.String _activityName) {
    this._activityName = _activityName;
  }
}
