/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */
package com.lf.lfopen.webservices.domain.workoutpreset.json;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * (no documentation provided)
 */
public class EquipmentData implements java.io.Serializable {

  @JsonIgnore
  private java.lang.Long _equipmentId;
  @JsonIgnore
  private java.lang.String _equipmentName;

  /**
   * Equipment Id
   */
  @JsonProperty("equipmentId")
  public java.lang.Long getEquipmentId() {
    return this._equipmentId;
  }

  /**
   * Equipment Id
   */
  @JsonProperty("equipmentId")
  public void setEquipmentId(java.lang.Long _equipmentId) {
    this._equipmentId = _equipmentId;
  }

  /**
   * Equipment Name
   */
  @JsonProperty("equipmentName")
  public java.lang.String getEquipmentName() {
    return this._equipmentName;
  }

  /**
   * Equipment Name
   */
  @JsonProperty("equipmentName")
  public void setEquipmentName(java.lang.String _equipmentName) {
    this._equipmentName = _equipmentName;
  }
}
