/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */
package com.lf.lfopen.webservices.domain.workoutpreset.json;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * (no documentation provided)
 */
public class WOParam implements java.io.Serializable {

  @JsonIgnore
  private java.lang.Double _min;
  @JsonIgnore
  private java.lang.Double _max;
  @JsonIgnore
  private java.lang.Double _defaultValue;
  @JsonIgnore
  private java.lang.String _param;
  @JsonIgnore
  private java.lang.String _unit;

  /**
   * (no documentation provided)
   */
  @JsonProperty("min")
  public java.lang.Double getMin() {
    return this._min;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("min")
  public void setMin(java.lang.Double _min) {
    this._min = _min;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("max")
  public java.lang.Double getMax() {
    return this._max;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("max")
  public void setMax(java.lang.Double _max) {
    this._max = _max;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("defaultValue")
  public java.lang.Double getDefaultValue() {
    return this._defaultValue;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("defaultValue")
  public void setDefaultValue(java.lang.Double _defaultValue) {
    this._defaultValue = _defaultValue;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("param")
  public java.lang.String getParam() {
    return this._param;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("param")
  public void setParam(java.lang.String _param) {
    this._param = _param;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("unit")
  public java.lang.String getUnit() {
    return this._unit;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("unit")
  public void setUnit(java.lang.String _unit) {
    this._unit = _unit;
  }
}
