package com.lf.lfopen.webservices.domain.workoutresult.json;import com.fasterxml.jackson.annotation.JsonIgnore;import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */





/**
 * (no documentation provided)
 */
public class CardioLifefitnessProgress extends com.lf.lfopen.webservices.domain.workoutresult.json.CardioWorkoutProgress {

  @JsonIgnore
  private com.lf.lfopen.webservices.domain.workoutresult.json.LifefitnessChange _valueChangeCalories;
  @JsonIgnore
  private com.lf.lfopen.webservices.domain.workoutresult.json.LifefitnessChange _valueChangeDistance;
  @JsonIgnore
  private com.lf.lfopen.webservices.domain.workoutresult.json.LifefitnessChange _valueChangeSpeed;
  @JsonIgnore
  private com.lf.lfopen.webservices.domain.workoutresult.json.LifefitnessChange _valueChangeHeartRate;
  @JsonIgnore
  private com.lf.lfopen.webservices.domain.workoutresult.json.LifefitnessChange _valueChangeDistanceClimbed;

  /**
   * Change in calorie in each time interval specified
   */
  @JsonProperty("valueChangeCalories")
  public com.lf.lfopen.webservices.domain.workoutresult.json.LifefitnessChange getValueChangeCalories() {
    return this._valueChangeCalories;
  }

  /**
   * Change in calorie in each time interval specified
   */
  @JsonProperty("valueChangeCalories")
  public void setValueChangeCalories(com.lf.lfopen.webservices.domain.workoutresult.json.LifefitnessChange _valueChangeCalories) {
    this._valueChangeCalories = _valueChangeCalories;
  }

  /**
   * Change in distance in each time interval specified
   */
  @JsonProperty("valueChangeDistance")
  public com.lf.lfopen.webservices.domain.workoutresult.json.LifefitnessChange getValueChangeDistance() {
    return this._valueChangeDistance;
  }

  /**
   * Change in distance in each time interval specified
   */
  @JsonProperty("valueChangeDistance")
  public void setValueChangeDistance(com.lf.lfopen.webservices.domain.workoutresult.json.LifefitnessChange _valueChangeDistance) {
    this._valueChangeDistance = _valueChangeDistance;
  }

  /**
   * Change in speed in each time interval specified
   */
  @JsonProperty("valueChangeSpeed")
  public com.lf.lfopen.webservices.domain.workoutresult.json.LifefitnessChange getValueChangeSpeed() {
    return this._valueChangeSpeed;
  }

  /**
   * Change in speed in each time interval specified
   */
  @JsonProperty("valueChangeSpeed")
  public void setValueChangeSpeed(com.lf.lfopen.webservices.domain.workoutresult.json.LifefitnessChange _valueChangeSpeed) {
    this._valueChangeSpeed = _valueChangeSpeed;
  }

  /**
   * Change in heart rate in each time interval specified
   */
  @JsonProperty("valueChangeHeartRate")
  public com.lf.lfopen.webservices.domain.workoutresult.json.LifefitnessChange getValueChangeHeartRate() {
    return this._valueChangeHeartRate;
  }

  /**
   * Change in heart rate in each time interval specified
   */
  @JsonProperty("valueChangeHeartRate")
  public void setValueChangeHeartRate(com.lf.lfopen.webservices.domain.workoutresult.json.LifefitnessChange _valueChangeHeartRate) {
    this._valueChangeHeartRate = _valueChangeHeartRate;
  }

  /**
   * Change in distance climbed for inclined workouts in each time interval specfied
   */
  @JsonProperty("valueChangeDistanceClimbed")
  public com.lf.lfopen.webservices.domain.workoutresult.json.LifefitnessChange getValueChangeDistanceClimbed() {
    return this._valueChangeDistanceClimbed;
  }

  /**
   * Change in distance climbed for inclined workouts in each time interval specfied
   */
  @JsonProperty("valueChangeDistanceClimbed")
  public void setValueChangeDistanceClimbed(com.lf.lfopen.webservices.domain.workoutresult.json.LifefitnessChange _valueChangeDistanceClimbed) {
    this._valueChangeDistanceClimbed = _valueChangeDistanceClimbed;
  }
}
