package com.lf.lfopen.webservices.domain.workoutresult.json;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */

/**
 * (no documentation provided)
 */
public class CardioDailyProgress implements java.io.Serializable {

	@JsonIgnore
	private java.lang.String _equipmentName;
	@JsonIgnore
	private java.lang.Long _equipmentId;
	@JsonIgnore
	private java.lang.String _workoutName;
	@JsonIgnore
	private java.lang.Double _distance;
	@JsonIgnore
	private java.lang.Double _duration;
	@JsonIgnore
	private java.lang.Double _calorie;
	@JsonIgnore
	private java.util.Date _date;

	/**
	 * 
	 */
	@JsonProperty("equipmentName")
	public java.lang.String getEquipmentName() {
		return this._equipmentName;
	}

	/**
	 * 
	 */
	@JsonProperty("equipmentName")
	public void setEquipmentName(java.lang.String _equipmentName) {
		this._equipmentName = _equipmentName;
	}

	/**
	 * 
	 */
	@JsonProperty("equipmentId")
	public java.lang.Long getEquipmentId() {
		return this._equipmentId;
	}

	/**
	 * 
	 */
	@JsonProperty("equipmentId")
	public void setEquipmentId(java.lang.Long _equipmentId) {
		this._equipmentId = _equipmentId;
	}

	/**
	 * workout name . Valid for manual cardio workout
	 */
	@JsonProperty("workoutName")
	public java.lang.String getWorkoutName() {
		return this._workoutName;
	}

	/**
	 * workout name . Valid for manual cardio workout
	 */
	@JsonProperty("workoutName")
	public void setWorkoutName(java.lang.String _workoutName) {
		this._workoutName = _workoutName;
	}

	/**
	 * Distance of the workout
	 */
	@JsonProperty("distance")
	public java.lang.Double getDistance() {
		return this._distance;
	}

	/**
	 * Distance of the workout
	 */
	@JsonProperty("distance")
	public void setDistance(java.lang.Double _distance) {
		this._distance = _distance;
	}

	/**
	 * Duration of the workout
	 */
	@JsonProperty("duration")
	public java.lang.Double getDuration() {
		return this._duration;
	}

	/**
	 * Duration of the workout
	 */
	@JsonProperty("duration")
	public void setDuration(java.lang.Double _duration) {
		this._duration = _duration;
	}

	/**
	 * Calorie for the workout
	 */
	@JsonProperty("calorie")
	public java.lang.Double getCalorie() {
		return this._calorie;
	}

	/**
	 * Calorie for the workout
	 */
	@JsonProperty("calorie")
	public void setCalorie(java.lang.Double _calorie) {
		this._calorie = _calorie;
	}

	/**
	 * (no documentation provided)
	 */
	@JsonProperty("date")
	public java.util.Date getDate() {
		return this._date;
	}

	/**
	 * (no documentation provided)
	 */
	@JsonProperty("date")
	public void setDate(java.util.Date _date) {
		this._date = _date;
	}
}
