package com.lf.lfopen.webservices.domain.workoutresult.json;import com.fasterxml.jackson.annotation.JsonIgnore;import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */




/**
 * (no documentation provided)
 */
public class GPSResultCoordinate implements java.io.Serializable {

  @JsonIgnore
  private java.lang.Double _latitude;
  @JsonIgnore
  private java.lang.Double _longitude;
  @JsonIgnore
  private java.lang.Boolean _pauseAfter;
  @JsonIgnore
  private java.util.Date _timestamp;
  @JsonIgnore
  private java.lang.Double _pace;
  @JsonIgnore
  private java.lang.Double _speed;
  @JsonIgnore
  private java.lang.Double _altitude;
  @JsonIgnore
  private java.lang.Double _calories;

  /**
   * The Latitude value of the coordinate of the GPS workout at a given time.
   */
  @JsonProperty("latitude")
  public java.lang.Double getLatitude() {
    return this._latitude;
  }

  /**
   * The Latitude value of the coordinate of the GPS workout at a given time.
   */
  @JsonProperty("latitude")
  public void setLatitude(java.lang.Double _latitude) {
    this._latitude = _latitude;
  }

  /**
   * The Longitude value of the coordinate of the GPS workout at a given time.
   */
  @JsonProperty("longitude")
  public java.lang.Double getLongitude() {
    return this._longitude;
  }

  /**
   * The Longitude value of the coordinate of the GPS workout at a given time.
   */
  @JsonProperty("longitude")
  public void setLongitude(java.lang.Double _longitude) {
    this._longitude = _longitude;
  }

  /**
   * Indicator if this coordinate is on the "pause workout" state.
   */
  @JsonProperty("pauseAfter")
  public java.lang.Boolean getPauseAfter() {
    return this._pauseAfter;
  }

  /**
   * Indicator if this coordinate is on the "pause workout" state.
   */
  @JsonProperty("pauseAfter")
  public void setPauseAfter(java.lang.Boolean _pauseAfter) {
    this._pauseAfter = _pauseAfter;
  }

  /**
   * Timestamp of the coordinate for the workout.
   */
  @JsonProperty("timestamp")
  public java.util.Date getTimestamp() {
    return this._timestamp;
  }

  /**
   * Timestamp of the coordinate for the workout.
   */
  @JsonProperty("timestamp")
  public void setTimestamp(java.util.Date _timestamp) {
    this._timestamp = _timestamp;
  }

  /**
   * Pace value as of coordinate timestamp. The unit (whether imperial or metric) follows the GPS Workout's Distance selected unit.
   * Unit is in seconds/km or seconds/mi.
   */
  @JsonProperty("pace")
  public java.lang.Double getPace() {
    return this._pace;
  }

  /**
   * Pace value as of coordinate timestamp. The unit (whether imperial or metric) follows the GPS Workout's Distance selected unit.
   * Unit is in seconds/km or seconds/mi.
   */
  @JsonProperty("pace")
  public void setPace(java.lang.Double _pace) {
    this._pace = _pace;
  }

  /**
   * Speed value as of coordinate timestamp. The unit (whether imperial or metric) follows the GPS Workout's Distance selected unit.
   * Unit is in kph or mph.
   */
  @JsonProperty("speed")
  public java.lang.Double getSpeed() {
    return this._speed;
  }

  /**
   * Speed value as of coordinate timestamp. The unit (whether imperial or metric) follows the GPS Workout's Distance selected unit.
   * Unit is in kph or mph.
   */
  @JsonProperty("speed")
  public void setSpeed(java.lang.Double _speed) {
    this._speed = _speed;
  }

  /**
   * Altitude / Elevation value as of coordinate timestamp. The unit (whether imperial or metric) follows the GPS Workout's Distance selected unit.
   * Unit is in meter or feet.
   */
  @JsonProperty("altitude")
  public java.lang.Double getAltitude() {
    return this._altitude;
  }

  /**
   * Altitude / Elevation value as of coordinate timestamp. The unit (whether imperial or metric) follows the GPS Workout's Distance selected unit.
   * Unit is in meter or feet.
   */
  @JsonProperty("altitude")
  public void setAltitude(java.lang.Double _altitude) {
    this._altitude = _altitude;
  }

  /**
   * Calories burned value as of coordinate timestamp.
   */
  @JsonProperty("calories")
  public java.lang.Double getCalories() {
    return this._calories;
  }

  /**
   * Calories burned value as of coordinate timestamp.
   */
  @JsonProperty("calories")
  public void setCalories(java.lang.Double _calories) {
    this._calories = _calories;
  }
}
