package com.lf.lfopen.webservices.domain.workoutresult.json;import com.fasterxml.jackson.annotation.JsonIgnore;import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */




/**
 * (no documentation provided)
 */
public class LifefitnessChange implements java.io.Serializable {

  @JsonIgnore
  private java.lang.String _timeChange;
  @JsonIgnore
  private java.lang.String _valueChange;

  /**
   * (no documentation provided)
   */
  @JsonProperty("timeChange")
  public java.lang.String getTimeChange() {
    return this._timeChange;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("timeChange")
  public void setTimeChange(java.lang.String _timeChange) {
    this._timeChange = _timeChange;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("valueChange")
  public java.lang.String getValueChange() {
    return this._valueChange;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("valueChange")
  public void setValueChange(java.lang.String _valueChange) {
    this._valueChange = _valueChange;
  }
}
