package com.lf.lfopen.webservices.domain.workoutresult.json;import com.fasterxml.jackson.annotation.JsonIgnore;import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */




/**
 * (no documentation provided)
 */
public class ManualCardioWorkoutResult extends com.lf.lfopen.webservices.domain.workoutresult.json.WorkoutResultOpen {

  @JsonIgnore
  private java.lang.Double _calories;
  @JsonIgnore
  private java.lang.Double _time;
  @JsonIgnore
  private java.lang.Double _distance;

  /**
   * Workout calories. Default value for empty should be 0 (zero).
   */
  @JsonProperty("calories")
  public java.lang.Double getCalories() {
    return this._calories;
  }

  /**
   * Workout calories. Default value for empty should be 0 (zero).
   */
  @JsonProperty("calories")
  public void setCalories(java.lang.Double _calories) {
    this._calories = _calories;
  }

  /**
   * Workout duration. Default value for empty should be 0 (zero).
   */
  @JsonProperty("time")
  public java.lang.Double getTime() {
    return this._time;
  }

  /**
   * Workout duration. Default value for empty should be 0 (zero).
   */
  @JsonProperty("time")
  public void setTime(java.lang.Double _time) {
    this._time = _time;
  }

  /**
   * Workout distance. Default value for empty should be 0 (zero).
   */
  @JsonProperty("distance")
  public java.lang.Double getDistance() {
    return this._distance;
  }

  /**
   * Workout distance. Default value for empty should be 0 (zero).
   */
  @JsonProperty("distance")
  public void setDistance(java.lang.Double _distance) {
    this._distance = _distance;
  }
}
