package com.lf.lfopen.webservices.domain.workoutresult.json;import com.fasterxml.jackson.annotation.JsonIgnore;import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */




/**
 * (no documentation provided)
 */
public class ManualStrengthWorkoutResult extends com.lf.lfopen.webservices.domain.workoutresult.json.WorkoutResultOpen {

  @JsonIgnore
  private java.util.Collection<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthResultSet> _strengthSets;
  @JsonIgnore
  private java.lang.Integer _intensity;
  @JsonIgnore
  private java.lang.Integer _duration;
  @JsonIgnore
  private java.lang.Double _weight;

  /**
   * Strength Set repetition. Minimum is 1, maximum is 5.
   */
  @JsonProperty("strengthSets")
  public java.util.Collection<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthResultSet> getStrengthSets() {
    return this._strengthSets;
  }

  /**
   * Strength Set repetition. Minimum is 1, maximum is 5.
   */
  @JsonProperty("strengthSets")
  public void setStrengthSets(java.util.Collection<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthResultSet> _strengthSets) {
    this._strengthSets = _strengthSets;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("intensity")
  public java.lang.Integer getIntensity() {
    return this._intensity;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("intensity")
  public void setIntensity(java.lang.Integer _intensity) {
    this._intensity = _intensity;
  }

  /**
   * Duration of the workout.Default value for empty should be 0 (zero).
   */
  @JsonProperty("duration")
  public java.lang.Integer getDuration() {
    return this._duration;
  }

  /**
   * Duration of the workout.Default value for empty should be 0 (zero).
   */
  @JsonProperty("duration")
  public void setDuration(java.lang.Integer _duration) {
    this._duration = _duration;
  }

  /**
   * Weight of the strength workout
   */
  @JsonProperty("weight")
  public java.lang.Double getWeight() {
    return this._weight;
  }

  /**
   * Weight of the strength workout
   */
  @JsonProperty("weight")
  public void setWeight(java.lang.Double _weight) {
    this._weight = _weight;
  }
}
