package com.lf.lfopen.webservices.domain.workoutresult.json;import com.fasterxml.jackson.annotation.JsonIgnore;import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */




/**
 * (no documentation provided)
 */
public class ResultProgressDailyData implements java.io.Serializable {

  @JsonIgnore
  private java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.CardioDailyProgress> _cardioDataDetails;
  @JsonIgnore
  private java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthDailyProgress> _strengthData;
  @JsonIgnore
  private java.lang.Double _calorie;
  @JsonIgnore
  private java.lang.Double _duration;
  @JsonIgnore
  private java.lang.Double _distance;
  @JsonIgnore
  private java.util.Date _date;
  @JsonIgnore
  private java.lang.String _unit;

  /**
   * 
   */
  @JsonProperty("cardioDataDetails")
  public java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.CardioDailyProgress> getCardioDataDetails() {
    return this._cardioDataDetails;
  }

  /**
   * 
   */
  @JsonProperty("cardioDataDetails")
  public void setCardioDataDetails(java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.CardioDailyProgress> _cardioDataDetails) {
    this._cardioDataDetails = _cardioDataDetails;
  }

  /**
   * Strength workout results
   */
  @JsonProperty("strengthData")
  public java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthDailyProgress> getStrengthData() {
    return this._strengthData;
  }

  /**
   * Strength workout results
   */
  @JsonProperty("strengthData")
  public void setStrengthData(java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthDailyProgress> _strengthData) {
    this._strengthData = _strengthData;
  }

  /**
   * total calories of the workouts for the date
   */
  @JsonProperty("calorie")
  public java.lang.Double getCalorie() {
    return this._calorie;
  }

  /**
   * total calories of the workouts for the date
   */
  @JsonProperty("calorie")
  public void setCalorie(java.lang.Double _calorie) {
    this._calorie = _calorie;
  }

  /**
   * total duration of the workouts for the date
   */
  @JsonProperty("duration")
  public java.lang.Double getDuration() {
    return this._duration;
  }

  /**
   * total duration of the workouts for the date
   */
  @JsonProperty("duration")
  public void setDuration(java.lang.Double _duration) {
    this._duration = _duration;
  }

  /**
   * total distance of the workouts for the date
   */
  @JsonProperty("distance")
  public java.lang.Double getDistance() {
    return this._distance;
  }

  /**
   * total distance of the workouts for the date
   */
  @JsonProperty("distance")
  public void setDistance(java.lang.Double _distance) {
    this._distance = _distance;
  }

  /**
   * Date of the workout
   */
  @JsonProperty("date")
  public java.util.Date getDate() {
    return this._date;
  }

  /**
   * Date of the workout
   */
  @JsonProperty("date")
  public void setDate(java.util.Date _date) {
    this._date = _date;
  }

  /**
   * 
   */
  @JsonProperty("unit")
  public java.lang.String getUnit() {
    return this._unit;
  }

  /**
   * 
   */
  @JsonProperty("unit")
  public void setUnit(java.lang.String _unit) {
    this._unit = _unit;
  }
}
