package com.lf.lfopen.webservices.domain.workoutresult.json;import com.fasterxml.jackson.annotation.JsonIgnore;import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */




/**
 * (no documentation provided)
 */
public class ResultProgressDaily implements java.io.Serializable {

  @JsonIgnore
  private java.util.Collection<com.lf.lfopen.webservices.domain.workoutresult.json.ResultProgressDailyData> _dailyResultsData;

  /**
   * (no documentation provided)
   */
  @JsonProperty("dailyResultsData")
  public java.util.Collection<com.lf.lfopen.webservices.domain.workoutresult.json.ResultProgressDailyData> getDailyResultsData() {
    return this._dailyResultsData;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("dailyResultsData")
  public void setDailyResultsData(java.util.Collection<com.lf.lfopen.webservices.domain.workoutresult.json.ResultProgressDailyData> _dailyResultsData) {
    this._dailyResultsData = _dailyResultsData;
  }
}
