package com.lf.lfopen.webservices.domain.workoutresult.json;import java.io.UnsupportedEncodingException;

import com.fasterxml.jackson.annotation.JsonIgnore;import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */




/**
 * (no documentation provided)
 */
public class ResultProgressWorkoutData implements java.io.Serializable {

  @JsonIgnore
  private java.lang.Double _distance;
  @JsonIgnore
  private java.lang.Double _duration;
  @JsonIgnore
  private java.lang.String _calorie;
  @JsonIgnore
  private java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.CardioWorkoutProgress> _cardioDataDetails;
  @JsonIgnore
  private java.lang.String _unit;
  @JsonIgnore
  private java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthWorkoutProgress> _strengthData;
  @JsonIgnore
  private java.lang.String _workoutName;
  @JsonIgnore
  private java.lang.Long _equipmentId;
  @JsonIgnore
  private java.lang.String _equipmentName;

  /**
   * Total distance of the workout
   */
  @JsonProperty("distance")
  public java.lang.Double getDistance() {
    return this._distance;
  }

  /**
   * Total distance of the workout
   */
  @JsonProperty("distance")
  public void setDistance(java.lang.Double _distance) {
    this._distance = _distance;
  }

  /**
   * Total distance of workout
   */
  @JsonProperty("duration")
  public java.lang.Double getDuration() {
    return this._duration;
  }

  /**
   * Total distance of workout
   */
  @JsonProperty("duration")
  public void setDuration(java.lang.Double _duration) {
    this._duration = _duration;
  }

  /**
   * Total calories of workout
   */
  @JsonProperty("calorie")
  public java.lang.String getCalorie() {
    return this._calorie;
  }

  /**
   * Total calories of workout
   */
  @JsonProperty("calorie")
  public void setCalorie(java.lang.String _calorie) {
    this._calorie = _calorie;
  }

  /**
   * 
   */
  @JsonProperty("cardioDataDetails")
  public java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.CardioWorkoutProgress> getCardioDataDetails() {
    return this._cardioDataDetails;
  }

  /**
   * 
   */
  @JsonProperty("cardioDataDetails")
  public void setCardioDataDetails(java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.CardioWorkoutProgress> _cardioDataDetails) {
    this._cardioDataDetails = _cardioDataDetails;
  }

  /**
   * 
   */
  @JsonProperty("unit")
  public java.lang.String getUnit() {
    return this._unit;
  }

  /**
   * 
   */
  @JsonProperty("unit")
  public void setUnit(java.lang.String _unit) {
    this._unit = _unit;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("strengthData")
  public java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthWorkoutProgress> getStrengthData() {
    return this._strengthData;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("strengthData")
  public void setStrengthData(java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthWorkoutProgress> _strengthData) {
    this._strengthData = _strengthData;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("workoutName")
  public java.lang.String getWorkoutName() {
    return this._workoutName;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("workoutName")
  public void setWorkoutName(java.lang.String _workoutName) {
    this._workoutName = _workoutName;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("equipmentId")
  public java.lang.Long getEquipmentId() {
    return this._equipmentId;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("equipmentId")
  public void setEquipmentId(java.lang.Long _equipmentId) {
    this._equipmentId = _equipmentId;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("equipmentName")
  public java.lang.String getEquipmentName() {
    if (this._equipmentName !=null) {
		try {
			this._equipmentName = new String(this._equipmentName.getBytes("iso8859-1"), "UTF-8");
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		} 
	}
	return this._equipmentName;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("equipmentName")
  public void setEquipmentName(java.lang.String _equipmentName) {
    this._equipmentName = _equipmentName;
  }
}
