package com.lf.lfopen.webservices.domain.workoutresult.json;import java.io.UnsupportedEncodingException;

import com.fasterxml.jackson.annotation.JsonIgnore;import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */




/**
 * (no documentation provided)
 */
public class ResultProgressManualStrengthWorkoutData implements java.io.Serializable {

  @JsonIgnore
  private java.lang.Double _duration;
  @JsonIgnore
  private java.lang.Double _calorie;
  @JsonIgnore
  private java.lang.String _workoutName;
  @JsonIgnore
  private java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthWorkoutProgress> _strengthData;
  @JsonIgnore
  private java.lang.String _unit;

  /**
   * Total duration of the workout
   */
  @JsonProperty("duration")
  public java.lang.Double getDuration() {
    return this._duration;
  }

  /**
   * Total duration of the workout
   */
  @JsonProperty("duration")
  public void setDuration(java.lang.Double _duration) {
    this._duration = _duration;
  }

  /**
   * Total calories of the workout
   */
  @JsonProperty("calorie")
  public java.lang.Double getCalorie() {
    return this._calorie;
  }

  /**
   * Total calories of the workout
   */
  @JsonProperty("calorie")
  public void setCalorie(java.lang.Double _calorie) {
    this._calorie = _calorie;
  }

  /**
   * workout name
   */
  @JsonProperty("workoutName")
  public java.lang.String getWorkoutName() {
	    if (this._workoutName !=null) {
			try {
				this._workoutName = new String(this._workoutName.getBytes("iso8859-1"), "UTF-8");
			} catch (UnsupportedEncodingException e) {
				e.printStackTrace();
			} 
		}
		return this._workoutName;
  }

  /**
   * workout name
   */
  @JsonProperty("workoutName")
  public void setWorkoutName(java.lang.String _workoutName) {
    this._workoutName = _workoutName;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("strengthData")
  public java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthWorkoutProgress> getStrengthData() {
    return this._strengthData;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("strengthData")
  public void setStrengthData(java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthWorkoutProgress> _strengthData) {
    this._strengthData = _strengthData;
  }

  /**
   * 
   */
  @JsonProperty("unit")
  public java.lang.String getUnit() {
    return this._unit;
  }

  /**
   * 
   */
  @JsonProperty("unit")
  public void setUnit(java.lang.String _unit) {
    this._unit = _unit;
  }
}
