package com.lf.lfopen.webservices.domain.workoutresult.json;import com.fasterxml.jackson.annotation.JsonIgnore;import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */




/**
 * (no documentation provided)
 */
public class StrengthDailyProgress implements java.io.Serializable {

  @JsonIgnore
  private java.util.Date _date;
  @JsonIgnore
  private java.lang.Double _calorie;
  @JsonIgnore
  private java.lang.String _strengthWorkoutName;
  @JsonIgnore
  private java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthResultSet> _strengthDataDetails;

  /**
   * (no documentation provided)
   */
  @JsonProperty("date")
  public java.util.Date getDate() {
    return this._date;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("date")
  public void setDate(java.util.Date _date) {
    this._date = _date;
  }

  /**
   * Calorie for the workout
   */
  @JsonProperty("calorie")
  public java.lang.Double getCalorie() {
    return this._calorie;
  }

  /**
   * Calorie for the workout
   */
  @JsonProperty("calorie")
  public void setCalorie(java.lang.Double _calorie) {
    this._calorie = _calorie;
  }

  /**
   * Strength workout name
   */
  @JsonProperty("strengthWorkoutName")
  public java.lang.String getStrengthWorkoutName() {
    return this._strengthWorkoutName;
  }

  /**
   * Strength workout name
   */
  @JsonProperty("strengthWorkoutName")
  public void setStrengthWorkoutName(java.lang.String _strengthWorkoutName) {
    this._strengthWorkoutName = _strengthWorkoutName;
  }

  /**
   * Strength additional details
   */
  @JsonProperty("strengthDataDetails")
  public java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthResultSet> getStrengthDataDetails() {
    return this._strengthDataDetails;
  }

  /**
   * Strength additional details
   */
  @JsonProperty("strengthDataDetails")
  public void setStrengthDataDetails(java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthResultSet> _strengthDataDetails) {
    this._strengthDataDetails = _strengthDataDetails;
  }
}
