package com.lf.lfopen.webservices.domain.workoutresult.json;import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonIgnore;import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */




/**
 * (no documentation provided)
 */
//@JsonAutoDetect()
public class StrengthWorkoutProgress implements java.io.Serializable {

  @JsonIgnore
  private java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthResultSet> _strengthDataDetails;
  @JsonIgnore
  private java.lang.Double _calorie;
  @JsonIgnore
  private java.util.Date _date;
  public java.lang.String dateString;

  public void setDateString(java.lang.String dateString) {
	this.dateString = dateString;
}

/**
   * (no documentation provided)
   */
  @JsonProperty("strengthDataDetails")
  public java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthResultSet> getStrengthDataDetails() {
    return this._strengthDataDetails;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("strengthDataDetails")
  public void setStrengthDataDetails(java.util.List<com.lf.lfopen.webservices.domain.workoutresult.json.StrengthResultSet> _strengthDataDetails) {
    this._strengthDataDetails = _strengthDataDetails;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("calorie")
  public java.lang.Double getCalorie() {
    return this._calorie;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("calorie")
  public void setCalorie(java.lang.Double _calorie) {
    this._calorie = _calorie;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("date")
  public java.util.Date getDate() {
    return this._date;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("date")
  public void setDate(java.util.Date _date) {
    this._date = _date;
  }

public java.lang.String getDateString() {
	return _date.toLocaleString();
}
  
  
}
