package com.lf.lfopen.webservices.domain.workoutresult.json;import com.fasterxml.jackson.annotation.JsonIgnore;import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */




/**
 * (no documentation provided)
 */
public class UserWorkoutInputVo implements java.io.Serializable {

  @JsonIgnore
  private java.lang.Double _calories;
  @JsonIgnore
  private java.lang.Long _activityId;
  @JsonIgnore
  private java.lang.Double _distance;
  @JsonIgnore
  private java.util.Date _dateTime;
  @JsonIgnore
  private java.lang.Long _duration;

  /**
   * (no documentation provided)
   */
  @JsonProperty("calories")
  public java.lang.Double getCalories() {
    return this._calories;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("calories")
  public void setCalories(java.lang.Double _calories) {
    this._calories = _calories;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("activityId")
  public java.lang.Long getActivityId() {
    return this._activityId;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("activityId")
  public void setActivityId(java.lang.Long _activityId) {
    this._activityId = _activityId;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("distance")
  public java.lang.Double getDistance() {
    return this._distance;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("distance")
  public void setDistance(java.lang.Double _distance) {
    this._distance = _distance;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("dateTime")
  public java.util.Date getDateTime() {
    return this._dateTime;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("dateTime")
  public void setDateTime(java.util.Date _dateTime) {
    this._dateTime = _dateTime;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("duration")
  public java.lang.Long getDuration() {
    return this._duration;
  }

  /**
   * (no documentation provided)
   */
  @JsonProperty("duration")
  public void setDuration(java.lang.Long _duration) {
    this._duration = _duration;
  }
}
