package com.lf.lfopen.webservices.domain.workoutresult.json;import com.fasterxml.jackson.annotation.JsonIgnore;import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * 
 *
 * Generated by <a href="http://enunciate.codehaus.org">Enunciate</a>.
 */




/**
 * (no documentation provided)
 */
public class WorkoutResultOpen implements java.io.Serializable {

  @JsonIgnore
  private java.lang.Boolean _facebookSharing;
  @JsonIgnore
  private java.util.Date _datePerformed;
  @JsonIgnore
  private java.lang.String _name;
  @JsonIgnore
  private java.lang.String _description;
  @JsonIgnore
  private java.lang.String _preferredUnit;
  @JsonIgnore
  private java.lang.String _fbShareMessage;

  /**
   * Facebook sharing flag.
   */
  @JsonProperty("facebookSharing")
  public java.lang.Boolean getFacebookSharing() {
    return this._facebookSharing;
  }

  /**
   * Facebook sharing flag.
   */
  @JsonProperty("facebookSharing")
  public void setFacebookSharing(java.lang.Boolean _facebookSharing) {
    this._facebookSharing = _facebookSharing;
  }

  /**
   * Date time of workout performed.
   * Format : 2011-02-12T17:16:10.180+08:00 (yyyy-MM-dd'T'HH:mm:ss.SSS+hh:mm).
   */
  @JsonProperty("datePerformed")
  public java.util.Date getDatePerformed() {
    return this._datePerformed;
  }

  /**
   * Date time of workout performed.
   * Format : 2011-02-12T17:16:10.180+08:00 (yyyy-MM-dd'T'HH:mm:ss.SSS+hh:mm).
   */
  @JsonProperty("datePerformed")
  public void setDatePerformed(java.util.Date _datePerformed) {
    this._datePerformed = _datePerformed;
  }

  /**
   * Workout Name.
   */
  @JsonProperty("name")
  public java.lang.String getName() {
    return this._name;
  }

  /**
   * Workout Name.
   */
  @JsonProperty("name")
  public void setName(java.lang.String _name) {
    this._name = _name;
  }

  /**
   * Workout description.
   */
  @JsonProperty("description")
  public java.lang.String getDescription() {
    return this._description;
  }

  /**
   * Workout description.
   */
  @JsonProperty("description")
  public void setDescription(java.lang.String _description) {
    this._description = _description;
  }

  /**
   * Unit representing the workout value. I for imperial, M for metric.
   */
  @JsonProperty("preferredUnit")
  public java.lang.String getPreferredUnit() {
    return this._preferredUnit;
  }

  /**
   * Unit representing the workout value. I for imperial, M for metric.
   */
  @JsonProperty("preferredUnit")
  public void setPreferredUnit(java.lang.String _preferredUnit) {
    this._preferredUnit = _preferredUnit;
  }

  /**
   * The message to be  posted to Facebook once the workout is saved.
   */
  @JsonProperty("fbShareMessage")
  public java.lang.String getFbShareMessage() {
    return this._fbShareMessage;
  }

  /**
   * The message to be  posted to Facebook once the workout is saved.
   */
  @JsonProperty("fbShareMessage")
  public void setFbShareMessage(java.lang.String _fbShareMessage) {
    this._fbShareMessage = _fbShareMessage;
  }
}
